In [2]:
import numpy as np
from numpy.random import randn

np.set_printoptions(precision=2, suppress=True)

creating arrays

In [3]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
len(x)

10

In [5]:
type(x)

numpy.ndarray

two-dimensional array

In [7]:
y = np.array([[10, 20, 30], [40, 50, 60]])
y

array([[10, 20, 30],
       [40, 50, 60]])

creating arrays via assigment

In [8]:
np.random.seed(25)
z = 36 * randn(6)
z

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [9]:
a = np.arange(1, 50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

performing arithmetic on arrays

In [10]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
x * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
[(i*2) for i in x]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [17]:
y

array([[10, 20, 30],
       [40, 50, 60]])

multiplying matrices and basic linear algebra

In [22]:
matrix = np.array([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
matrix

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [23]:
matrix2 = np.array([[4, 5, 6], [40, 50, 60], [400, 500, 600]])
matrix2

array([[  4,   5,   6],
       [ 40,  50,  60],
       [400, 500, 600]])

In [24]:
matrix * matrix2

array([[     4,     10,     18],
       [   400,   1000,   1800],
       [ 40000, 100000, 180000]])

In [25]:
np.dot(matrix, matrix2)

array([[  1284,   1605,   1926],
       [ 12840,  16050,  19260],
       [128400, 160500, 192600]])

In [26]:
matrix ** 2

array([[    1,     4,     9],
       [  100,   400,   900],
       [10000, 40000, 90000]])

In [27]:
matrix2 - matrix

array([[  3,   3,   3],
       [ 30,  30,  30],
       [300, 300, 300]])