In [2]:
import numpy as np
from numpy.random import randn

np.set_printoptions(precision=2, suppress=True)

creating arrays

In [3]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
len(x)

10

In [5]:
type(x)

numpy.ndarray

two-dimensional array

In [7]:
y = np.array([[10, 20, 30], [40, 50, 60]])
y

array([[10, 20, 30],
       [40, 50, 60]])

creating arrays via assigment

In [8]:
np.random.seed(25)
z = 36 * randn(6)
z

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [9]:
a = np.arange(1, 50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

performing arithmetic on arrays

In [10]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
x * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [16]:
[(i*2) for i in x]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [17]:
y

array([[10, 20, 30],
       [40, 50, 60]])

multiplying matrices and basic linear algebra

In [22]:
matrix = np.array([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
matrix

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [23]:
matrix2 = np.array([[4, 5, 6], [40, 50, 60], [400, 500, 600]])
matrix2

array([[  4,   5,   6],
       [ 40,  50,  60],
       [400, 500, 600]])

In [24]:
matrix * matrix2

array([[     4,     10,     18],
       [   400,   1000,   1800],
       [ 40000, 100000, 180000]])

In [25]:
np.dot(matrix, matrix2)

array([[  1284,   1605,   1926],
       [ 12840,  16050,  19260],
       [128400, 160500, 192600]])

In [26]:
matrix ** 2

array([[    1,     4,     9],
       [  100,   400,   900],
       [10000, 40000, 90000]])

In [27]:
matrix2 - matrix

array([[  3,   3,   3],
       [ 30,  30,  30],
       [300, 300, 300]])

multiplying matrices

In [28]:
matrix 

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [29]:
matrix2

array([[  4,   5,   6],
       [ 40,  50,  60],
       [400, 500, 600]])

In [30]:
matrix * matrix2

array([[     4,     10,     18],
       [   400,   1000,   1800],
       [ 40000, 100000, 180000]])

In [31]:
np.dot(matrix, matrix2) # np.dot: matrix multiplication

array([[  1284,   1605,   1926],
       [ 12840,  16050,  19260],
       [128400, 160500, 192600]])

GENERATING SUMMARY STATISTICS USING PANDAS AND SCIPY

In [33]:
import pandas as pd
from pandas import Series, DataFrame
import scipy
from scipy import stats

In [35]:
df = pd.read_csv('./data/mtcars.csv')
df.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
df.head()

car_names   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2

[5 rows x 12 columns]

In [36]:
df.sum()

car_names    Mazda RX4Mazda RX4 WagDatsun 710Hornet 4 Drive...
mpg                                                      642.9
cyl                                                        198
disp                                                    7383.1
hp                                                        4694
drat                                                    115.09
wt                                                     102.952
qsec                                                    571.16
vs                                                          14
am                                                          13
gear                                                       118
carb                                                        90
dtype: object

In [37]:
df.sum(axis=1) # sum of each row

/var/folders/h0/c9qylmn17q1g2jkn_w5pzpd40000gn/T/ipykernel_92315/1459321664.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.sum(axis=1)


0     328.980
1     329.795
2     259.580
3     426.135
4     590.310
5     385.540
6     656.920
7     270.980
8     299.570
9     350.460
10    349.660
11    510.740
12    511.500
13    509.850
14    728.560
15    726.644
16    725.695
17    213.850
18    195.165
19    206.955
20    273.775
21    519.650
22    506.085
23    646.280
24    631.175
25    208.215
26    272.570
27    273.683
28    670.690
29    379.590
30    694.710
31    288.890
dtype: float64

In [40]:
df['mpg'].sum()

642.9000000000001

In [38]:
df.median()

/var/folders/h0/c9qylmn17q1g2jkn_w5pzpd40000gn/T/ipykernel_92315/530051474.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()


mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [39]:
df['mpg'].median()

19.2

In [41]:
df.mean()

/var/folders/h0/c9qylmn17q1g2jkn_w5pzpd40000gn/T/ipykernel_92315/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [42]:
df.carb.mean()

2.8125

In [43]:
df.max()

car_names    Volvo 142E
mpg                33.9
cyl                   8
disp              472.0
hp                  335
drat               4.93
wt                5.424
qsec               22.9
vs                    1
am                    1
gear                  5
carb                  8
dtype: object

In [44]:
df.min()

car_names    AMC Javelin
mpg                 10.4
cyl                    4
disp                71.1
hp                    52
drat                2.76
wt                 1.513
qsec                14.5
vs                     0
am                     0
gear                   3
carb                   1
dtype: object

In [46]:
df.mpg.idxmax()

19

LOOKING AT SUMMARY STATISTICS THAT DESCRIBE VARIABLE DISTRIBUTION

In [47]:
df.std() # standard deviation

/var/folders/h0/c9qylmn17q1g2jkn_w5pzpd40000gn/T/ipykernel_92315/3390915376.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std()


mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [48]:
df.mpg.std()

6.026948052089104

In [49]:
df.var() # variance

/var/folders/h0/c9qylmn17q1g2jkn_w5pzpd40000gn/T/ipykernel_92315/1568254755.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.var()


mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64

In [50]:
df.wt.var()

0.9573789677419354

In [51]:
df.value_counts()

car_names            mpg   cyl  disp   hp   drat  wt     qsec   vs  am  gear  carb
AMC Javelin          15.2  8    304.0  150  3.15  3.435  17.30  0   0   3     2       1
Cadillac Fleetwood   10.4  8    472.0  205  2.93  5.250  17.98  0   0   3     4       1
Valiant              18.1  6    225.0  105  2.76  3.460  20.22  1   0   3     1       1
Toyota Corona        21.5  4    120.1  97   3.70  2.465  20.01  1   0   3     1       1
Toyota Corolla       33.9  4    71.1   65   4.22  1.835  19.90  1   1   4     1       1
Porsche 914-2        26.0  4    120.3  91   4.43  2.140  16.70  0   1   5     2       1
Pontiac Firebird     19.2  8    400.0  175  3.08  3.845  17.05  0   0   3     2       1
Merc 450SLC          15.2  8    275.8  180  3.07  3.780  18.00  0   0   3     3       1
Merc 450SL           17.3  8    275.8  180  3.07  3.730  17.60  0   0   3     3       1
Merc 450SE           16.4  8    275.8  180  3.07  4.070  17.40  0   0   3     3       1
Merc 280C            17.8  6    167.6

In [53]:
df.gear.value_counts()

3    15
4    12
5     5
Name: gear, dtype: int64

In [54]:
df.describe()

mpg        cyl        disp  ...         am       gear     carb
count  32.000000  32.000000   32.000000  ...  32.000000  32.000000  32.0000
mean   20.090625   6.187500  230.721875  ...   0.406250   3.687500   2.8125
std     6.026948   1.785922  123.938694  ...   0.498991   0.737804   1.6152
min    10.400000   4.000000   71.100000  ...   0.000000   3.000000   1.0000
25%    15.425000   4.000000  120.825000  ...   0.000000   3.000000   2.0000
50%    19.200000   6.000000  196.300000  ...   0.000000   4.000000   2.0000
75%    22.800000   8.000000  326.000000  ...   1.000000   4.000000   4.0000
max    33.900000   8.000000  472.000000  ...   1.000000   5.000000   8.0000

[8 rows x 11 columns]